version: "3"

services:
  api:
    build:
      context: "."
      dockerfile: "./app/Dockerfile.api"
    container_name: api
    image: "text_anonymizer:api"
    ports:
    - "8000:8000"
    working_dir: "/text_anonymize/api"
    networks:
      - anonymize-net
    entrypoint: python3
    command:
      api.py
    restart: always

  webapp:
    build:
      context: "."
      dockerfile: "./app/Dockerfile.webapp"
    container_name: app
    image: "text_anonymizer:app"
    ports:
    - "80:8501"
    environment:
    - API_CONT_NAME='text_api'
    - API_CONT_PORT='8000'
    networks:
       - anonymize-net
    entrypoint: streamlit
    command:
      run frontend.py
    depends_on:
      - api
    restart: always

networks:
  anonymize-net:
    driver: bridge