version: "3"

services:
  api:
    build:
      context: "."
      dockerfile: "Dockerfile.api"
    container_name: text_api
    image: "text_anonymizer:api"
    ports:
    - "8000:8000"
    working_dir: "/text_anonymize/api"
    networks:
      - anonymize-net
    entrypoint: uvicorn
    command:
      api:api --proxy-headers --host 0.0.0.0 --port 8000
    restart: always

  webapp:
    build:
      context: "."
      dockerfile: "Dockerfile.webapp"
    container_name: text_app
    image: "text_anonymizer:app"
    ports:
    - "80:8501"
    networks:
       - anonymize-net
    entrypoint: streamlit run
    command:
      --server.port 8501 "Text Anonymizer.py"
    depends_on:
      - api
    restart: always

networks:
  anonymize-net:
    driver: bridge