# get base image
FROM python:3.9.1

WORKDIR /text_anonymize/web_app

RUN apt-get update

RUN pip install spacy streamlit

RUN python3 -m spacy download en_core_web_sm

# take note to update email if you're not me 😁️
# streamlit-specific commands
RUN mkdir -p /root/.streamlit
RUN bash -c 'echo -e "\
            [general]\n\
            email = \"\"\n\
            " > /root/.streamlit/credentials.toml'            
RUN bash -c 'echo -e "\
            [server]\n\
            enableCORS = false\n\
            " > /root/.streamlit/config.toml'

COPY . /text_anonymize/web_app/

EXPOSE 8501

CMD [ "streamlit", "run", "app/frontend.py" ]