# get base image
FROM python:3.9.1

WORKDIR /text_anonymize/api

RUN apt-get update

RUN pip install spacy==3.1 uvicorn==0.14.0 fastapi==0.70.0

RUN python3 -m spacy download en_core_web_sm

COPY ./app /text_anonymize/api/

EXPOSE 8000

ENTRYPOINT [ "python3" ]

CMD [ "api.py" ]